# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"
require "active_record"
require "erb"

include ActiveRecord::Tasks
DatabaseTasks.env = ENV["RACK_ENV"] ||= "development"
DatabaseTasks.root = File.expand_path("spec/support", __dir__)
DatabaseTasks.db_dir = File.expand_path("db", DatabaseTasks.root)
DatabaseTasks.migrations_paths = [File.expand_path("db/migrate", DatabaseTasks.root)]
DatabaseTasks.database_configuration = YAML.load(
  ERB.new(File.read(File.expand_path("database.yml", DatabaseTasks.root))).result,
  aliases: true
)
# other settings...

task :environment do
  ActiveRecord::Base.configurations = DatabaseTasks.database_configuration
  ActiveRecord::Base.establish_connection DatabaseTasks.env.to_sym
end
load "active_record/railties/databases.rake"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

task default: %i[spec rubocop]
