image: ruby:2.3

before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

cache:
  key: "$CI_JOB_STAGE/$CI_COMMIT_REF_NAME"
  untracked: true

# 定义 stages
stages:
  - build
  - test

rspec:
  stage: test
  script:
    - bundle exec rspec

rubocop:
  stage: test
  script:
    - bundle exec rubocop
