require: rubocop-rspec

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  Exclude:
    - "Gemfile.lock"
    - "spec/dummy/Gemfile.lock"
    - "spec/dummy/db/schema.rb"
  TargetRubyVersion: 2.5
