---
include:
  - "**/*.rb"
exclude:
  - "**/spec/**/*"
  - "**/test/**/*"
  - "**/vendor/**/*"
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - rubocop
  - typecheck:strict
require_paths: []
plugins: []
max_files: 5000
