# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in authcat-account.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.7"

gem "activerecord", "~> 5.2"

gem "database_cleaner", "~> 1.5"

gem "pg", require: false
gem "sqlite3"

gem "bcrypt"
gem "rotp",         require: false
gem "blind_index",  require: false
gem "lockbox",      require: false
gem "phonelib",     require: false
gem "valid_email2", require: false

gem "state_machines-activerecord", require: false

path ".." do
  gem "authcat-identifier"
  gem "authcat-multi_factor"
  gem "authcat-password"
end
