version: "3"
services:
  dev:
    user: vscode
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - zsh_history:/commandhistory
      - bundle:/usr/local/bundle
      - ..:/workspace:delegated

    # ports:
    #   - 3000:3000
    depends_on:
      - postgres
    environment:
      - LANG=C.UTF-8
      - BUNDLE_JOBS=8
    command: ["sleep", "infinity"]
    # command: ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]

  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=authcat
      - POSTGRES_PASSWORD=authcat

volumes:
  zsh_history:
  bundle:
  postgres:
