version: "3"
services:
  dev:
    user: vscode:vscode
    platform: linux/x86_64
    working_dir: /workspaces/authcat
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.2
        NODE_VERSION: 14
    volumes:
      - bundle:/usr/local/bundle
      - gems:/usr/local/rvm/gems
      - tmp_cache:/workspaces/authcat/playground/tmp/cache
      - node_modules:/workspaces/authcat/playground/node_modules

    # ports:
    #   - 3000:3000
    depends_on:
      - postgres
    environment:
      - LANG=C.UTF-8
      - BUNDLE_JOBS=8
    command: [ "sleep", "infinity" ]
    # command: ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]

  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=authcat
      - POSTGRES_PASSWORD=authcat

volumes:
  bundle:
  gems:
  postgres:
  tmp_cache:
  node_modules:
