# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

ENV["RACK_ENV"] ||= "development"

load "authcat/support/databases.rake"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

task default: %i[spec rubocop]
