# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"
require "active_record"

include ActiveRecord::Tasks
DatabaseTasks.env = ENV["RACK_ENV"] || "development"
DatabaseTasks.root = File.expand_path(".", __dir__)
DatabaseTasks.db_dir = File.expand_path("spec/support/db", __dir__)
DatabaseTasks.migrations_paths = [
  File.expand_path("spec/support/db/migrate", __dir__),
  File.expand_path("db/migrate", __dir__)
]
DatabaseTasks.database_configuration = YAML.load_file(File.expand_path("spec/support/database.yml", __dir__),
                                                      aliases: true)
# other settings...

task :environment do
  ActiveRecord::Base.configurations = DatabaseTasks.database_configuration
  ActiveRecord::Base.establish_connection DatabaseTasks.env.to_sym
end
load "active_record/railties/databases.rake"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

task default: %i[spec rubocop]
