# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in authcat-password.gemspec
gemspec

gem 'activerecord', '~> 5.2'

gem 'rake', '~> 12.0'
gem 'rspec', '~> 3.5'

gem 'database_cleaner', '~> 1.5'

gem 'simplecov', require: false

gem 'pg', require: false
gem 'sqlite3'

gem 'bcrypt', require: false
gem 'rotp', require: false
gem 'webauthn', require: false

path '..' do
  gem 'authcat-password', require: false
end
