# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in authcat-identity.gemspec
gemspec

gem 'rake', '~> 12.0'
gem 'rspec', '~> 3.0'

gem 'activerecord', '~> 5.2'

gem 'database_cleaner', '~> 1.5'

gem 'pg', require: false
gem 'sqlite3'

gem 'email_validator'
