# pulled from repo
name: "RSpec"

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gem_name:
          - authcat-credential
          - authcat-identifier
          - authcat-idp
          - authcat-password
          - authcat-session
          - authcat-webauthn
        ruby_version: ["3.0", "3.1", "3.2"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ matrix.gem_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # If running on a self-hosted runner, check it meets the requirements
      # listed at https://github.com/ruby/setup-ruby#using-self-hosted-runners
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: RSpec run
        run: bundle exec rspec
